// Приемущество с finally возникает, если в блоке catch пробрасывать ошибку наверх.
